// Code generated by "stringer -type=IsoCode639_1"; DO NOT EDIT.

package lingua

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AF-0]
	_ = x[AR-1]
	_ = x[AZ-2]
	_ = x[BE-3]
	_ = x[BG-4]
	_ = x[BN-5]
	_ = x[BS-6]
	_ = x[CA-7]
	_ = x[CS-8]
	_ = x[CY-9]
	_ = x[DA-10]
	_ = x[DE-11]
	_ = x[EL-12]
	_ = x[EN-13]
	_ = x[EO-14]
	_ = x[ES-15]
	_ = x[ET-16]
	_ = x[EU-17]
	_ = x[FA-18]
	_ = x[FI-19]
	_ = x[FR-20]
	_ = x[GA-21]
	_ = x[GU-22]
	_ = x[HE-23]
	_ = x[HI-24]
	_ = x[HR-25]
	_ = x[HU-26]
	_ = x[HY-27]
	_ = x[ID-28]
	_ = x[IS-29]
	_ = x[IT-30]
	_ = x[JA-31]
	_ = x[KA-32]
	_ = x[KK-33]
	_ = x[KO-34]
	_ = x[LA-35]
	_ = x[LG-36]
	_ = x[LT-37]
	_ = x[LV-38]
	_ = x[MK-39]
	_ = x[MN-40]
	_ = x[MR-41]
	_ = x[MS-42]
	_ = x[NB-43]
	_ = x[NL-44]
	_ = x[NN-45]
	_ = x[PA-46]
	_ = x[PL-47]
	_ = x[PT-48]
	_ = x[RO-49]
	_ = x[RU-50]
	_ = x[SK-51]
	_ = x[SL-52]
	_ = x[SN-53]
	_ = x[SO-54]
	_ = x[SQ-55]
	_ = x[SR-56]
	_ = x[ST-57]
	_ = x[SV-58]
	_ = x[SW-59]
	_ = x[TA-60]
	_ = x[TE-61]
	_ = x[TH-62]
	_ = x[TL-63]
	_ = x[TN-64]
	_ = x[TR-65]
	_ = x[TS-66]
	_ = x[UK-67]
	_ = x[UR-68]
	_ = x[VI-69]
	_ = x[XH-70]
	_ = x[YO-71]
	_ = x[ZH-72]
	_ = x[ZU-73]
}

const _IsoCode639_1_name = "AFARAZBEBGBNBSCACSCYDADEELENEOESETEUFAFIFRGAGUHEHIHRHUHYIDISITJAKAKKKOLALGLTLVMKMNMRMSNBNLNNPAPLPTRORUSKSLSNSOSQSRSTSVSWTATETHTLTNTRTSUKURVIXHYOZHZU"

var _IsoCode639_1_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148}

func (i IsoCode639_1) String() string {
	if i < 0 || i >= IsoCode639_1(len(_IsoCode639_1_index)-1) {
		return "IsoCode639_1(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IsoCode639_1_name[_IsoCode639_1_index[i]:_IsoCode639_1_index[i+1]]
}
